### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jorgicio** [gigitux/gtkwhats#11]
Hi!

I maintain this package for my distro, Gentoo, and I find the application very good at start.
Just one question: What about the license? I couldn't find any information about that. Indeed, there's no LICENSE file in this repo.

Please, clarify this.

Thank you!

**Comment by gigitux** [comment]
@jorgicio 
Hi!
Thanks for becoming the package maintainer of this project on gentoo, if you pass me the name of the package I add the readme information (or you can do it with a PR)

The license is MIT!
Now I update the master repo

**Comment by jorgicio** [comment]
Thank you! Ebuild modified.
The package is gtkwhats (or net-im/gtkwhats). My repo is https://github.com/jorgicio/jorgicio-gentoo-overlay.
There are the instructions for adding my overlay and then, install the gtkwhats package.

Greetings!
