### ISSUE TITLE
doesnt support recording voice messages

### ISSUE THREAD

**Issue by emanuelserpa** [gigitux/gtkwhats#17]
I don't know if this is a compatibility issue with webkit

**Comment by gigitux** [comment]
Are you sure that do you have codecs installed?

**Comment by gmagic** [comment]
i use flatpak and i used to set some permissions for app. And i now can listen to voice messages.

**Comment by gigitux** [comment]
Theoretically with fedora the permissions are all active by default. What distribution do you use?

**Comment by emanuelserpa** [comment]
I can listen, but I can't send voice messages.

I used a app based on electron (chromium) and sending messages worked fine.

**Comment by emanuelserpa** [comment]
QtWaW solved this problem

https://gitlab.com/scarpetta/qtwaw/-/merge_requests/1

**Comment by gigitux** [comment]
Hello!
Thanks for sharing this link with me.

I do not hide from you that I am finding it a bit difficult to enable permissions with the API that gtk-rs provides.

In the coming days I will continue to take a look at it!

**Comment by gigitux** [comment]
Hi! Updates: I did a lot of research, but unfortunately I got the confirmation: the current version of webkit that is in flatpak has not enabled access to mediaDevice

https://twitter.com/WebKitGTK/status/1313574533408985090

For a proof: Download epiphany browser and try to use the microphone or the webcam: there is no way

:(
