### ISSUE TITLE
Where are donwloaded files stored?

### ISSUE THREAD

**Issue by protito** [gigitux/gtkwhats#19]
Hi, 

Running on Pop_os 20.04 Received a pdf file and download seems to work. but cant find where the file was stored.Mauby adding a "Open" link in the download like in the official app would help.

**Comment by Doriangaensslen** [comment]
Exactly the same issue here :+1:

**Comment by gigitux** [comment]
Hello,
thanks for opening an issue!

The bug has been fixed (#28 ). I will release a new release soon
