### ISSUE TITLE
Feature Request: The ability to press control + V to paste items.

### ISSUE THREAD

**Issue by Joe23232** [gigitux/gtkwhats#21]
I wanted to suggest a feature request which is that if I copied an image or something, I wish I could press `ctrl` + `v` to paste the item, just like with the original whatsapp for Windows.

**Comment by gigitux** [comment]
I did some tests and it already works

**Comment by Joe23232** [comment]
@gigitux Hey man I am again trying this feature and it is not working. I am not too sure what this is happening?
