### ISSUE TITLE
How do I run gtkwhats?

### ISSUE THREAD

**Issue by Joe23232** [gigitux/gtkwhats#22]
I compiled it from source and it did launch successfully, but after closing the application I am not too sure where to launch it from? Inside `gtkwhats/target/debug/` there is a file `gtkwhats` that has been marked as executable, I tried to launch it but I get this error message (when launching from the terminal):

`(gtkwhats:66463): GLib-GIO-ERROR **: 00:40:14.609: Settings schema 'com.gigitux.gtkwhats' is not installed`.

Where do I launch this from?

**Comment by gigitux** [comment]
You need pass a valid path gschema like this
`GSETTINGS_SCHEMA_DIR=./data  ./gtkwhats`
