### ISSUE TITLE
The gtk theme is not applied and full screen is also not implimented

### ISSUE THREAD

**Issue by Xanaxus** [gigitux/gtkwhats#23]
![image](https://user-images.githubusercontent.com/53279068/90623670-6cd07900-e234-11ea-8a55-6c72afb25e2c.png)
I am using pop os/gnome, and have applied mac os theme for my applications.

**Comment by 12buntu** [comment]
I'm having the same issue, thinking about trying to compile it myself to see if it's a problem with flatpak

**Comment by gigitux** [comment]
I think that it is a flatpak problem.

Check this https://hkdb.medium.com/flatpak-custom-gtk-theme-updater-4e053ebd003
