### ISSUE TITLE
The timezone at the Linux Pop_OS is not respected

### ISSUE THREAD

**Issue by cgrio** [gigitux/gtkwhats#29]
I am from Brazil and my system time is 5:50 AM and the time at the messages shows 8:48 AM. 
It's a little issue and I love de app.

**Comment by gigitux** [comment]
Hi, what language do you see whatsapp in? Is it the same you see on the web? (if it's English, most likely there is no whatsapp version in your language)

Sorry for the delay :(

**Comment by gigitux** [comment]
Duplicate #13
